services:
  app:
    image: ${IMAGE_NAME:-relojoaria-luti:latest}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    env_file:
      - .env
    container_name: luti-relogios-app
